### ISSUE TITLE
Adding  25 after a % character in password

### ISSUE THREAD

**Issue by Daxcor69** [euberdeveloper/mongoback#24]
Hello,

so I have a password that has 3 % in it.  Each % is anteceded by the characters 25.  so a password  blob%stuff becomes blob%25stuff.  There must be some sort of encoding that is screwing with the % in the password option. I am seeing this in the error message when it shows the assembled in the uri string.  I am getting bad auth error and the only thing I can see different is the password, with these additional characters added in.

Brad

**Comment by euberdeveloper** [comment]
Yes, I can confirm that % urlencoded is %25

**Comment by Daxcor69** [comment]
That was the issue, I changed the password to remove the special characters.  I will have a look when I have time to see if I can find out who is encoding the characters.

**Comment by euberdeveloper** [comment]
The password is encoded from [this line](https://github.com/euberdeveloper/mongoback/blob/2661856e53180de52bc37684a3ae18daf3de07cd/source/utils/options/mergeOptions.ts#L19), but I thought that in order to be used by mongoexport it was necessary to do it manually, not that it expected the non-urlencoded pwd

**Comment by euberdeveloper** [comment]
I did some trials with the raw mongoexport and it works when in the --uri the string is urlencoded (%25 works, % does not), so I think that this is the expected behaviour
