### ISSUE TITLE
Package Size is heavy

### ISSUE THREAD

**Issue by aqualaguna** [euberdeveloper/mongoback#3]
you must kidding me. your package is awesome but its heavy.
82MB?

![Screenshot from 2020-09-11 08-57-00](https://user-images.githubusercontent.com/16866837/92841788-f676ff00-f40c-11ea-8f25-8ea31e79d379.png)
what is it make it heavy please make it clear.

**Comment by euberdeveloper** [comment]
Thank you, I don't know why I didn't notice that.
It's a long story... I did this package in order to export comfortably a database that was in the raspberry inside an electric car built by [us](https://eagletrt.it/).

To test the npm package, I populated the local mongodb with the data of the car and tried the functions over that database. I accidentally added that data of 80MB in the dist/source and published it on npm :laughing:

The new version now is ok, I also use a different/smaller dataset to test the package.

The package was also used to create [this](https://github.com/euberdeveloper/eagletrt-telemetria-exporter) if you are curious.

Thank you again
